// submit a request for account creation for the user
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_CLEANUP = 'REGISTER_CLEANUP';

// allows a user to login once his/her account has been approved
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_CLEANUP = 'LOGIN_CLEANUP';

// get profile
export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const GET_PROFILE_CLEANUP = 'GET_PROFILE_CLEANUP';

// get servers
export const GET_SERVERS_START = 'GET_SERVERS_START';
export const GET_SERVERS_SUCCESS = 'GET_SERVERS_SUCCESS';
export const GET_SERVERS_FAIL = 'GET_SERVERS_FAIL';
export const GET_SERVERS_CLEANUP = 'GET_SERVERS_CLEANUP';

// get single server details
export const GET_SINGLE_SERVER_START = 'GET_SINGLE_SERVER_START';
export const GET_SINGLE_SERVER_SUCCESS = 'GET_SINGLE_SERVER_SUCCESS';
export const GET_SINGLE_SERVER_FAIL = 'GET_SINGLE_SERVER_FAIL';
export const GET_SINGLE_SERVER_CLEANUP = 'GET_SINGLE_SERVER_CLEANUP';

// stop single server
export const STOP_SINGLE_SERVER_START = 'STOP_SINGLE_SERVER_START';
export const STOP_SINGLE_SERVER_SUCCESS = 'STOP_SINGLE_SERVER_SUCCESS';
export const STOP_SINGLE_SERVER_FAIL = 'STOP_SINGLE_SERVER_FAIL';
export const STOP_SINGLE_SERVER_CLEANUP = 'STOP_SINGLE_SERVER_CLEANUP';

// start single server
export const START_SINGLE_SERVER_START = 'START_SINGLE_SERVER_START';
export const START_SINGLE_SERVER_SUCCESS = 'START_SINGLE_SERVER_SUCCESS';
export const START_SINGLE_SERVER_FAIL = 'START_SINGLE_SERVER_FAIL';
export const START_SINGLE_SERVER_CLEANUP = 'START_SINGLE_SERVER_CLEANUP';

// reboot hard single server
export const REBOOT_HARD_SINGLE_SERVER_START =
  'REBOOT_HARD_SINGLE_SERVER_START';
export const REBOOT_HARD_SINGLE_SERVER_SUCCESS =
  'REBOOT_HARD_SINGLE_SERVER_SUCCESS';
export const REBOOT_HARD_SINGLE_SERVER_FAIL = 'REBOOT_HARD_SINGLE_SERVER_FAIL';
export const REBOOT_HARD_SINGLE_SERVER_CLEANUP =
  'REBOOT_HARD_SINGLE_SERVER_CLEANUP';

// reboot soft single server
export const REBOOT_SOFT_SINGLE_SERVER_START =
  'REBOOT_SOFT_SINGLE_SERVER_START';
export const REBOOT_SOFT_SINGLE_SERVER_SUCCESS =
  'REBOOT_SOFT_SINGLE_SERVER_SUCCESS';
export const REBOOT_SOFT_SINGLE_SERVER_FAIL = 'REBOOT_SOFT_SINGLE_SERVER_FAIL';
export const REBOOT_SOFT_SINGLE_SERVER_CLEANUP =
  'REBOOT_SOFT_SINGLE_SERVER_CLEANUP';

// delete single server
export const DELETE_SINGLE_SERVER_START = 'DELETE_SINGLE_SERVER_START';
export const DELETE_SINGLE_SERVER_SUCCESS = 'DELETE_SINGLE_SERVER_SUCCESS';
export const DELETE_SINGLE_SERVER_FAIL = 'DELETE_SINGLE_SERVER_FAIL';
export const DELETE_SINGLE_SERVER_CLEANUP = 'DELETE_SINGLE_SERVER_CLEANUP';

// create server
export const CREATE_SERVER_START = 'CREATE_SERVER_START';
export const CREATE_SERVER_SUCCESS = 'CREATE_SERVER_SUCCESS';
export const CREATE_SERVER_FAIL = 'CREATE_SERVER_FAIL';
export const CREATE_SERVER_CLEANUP = 'CREATE_SERVER_CLEANUP';

// get key pairs
export const GET_KEY_PAIRS_START = 'GET_KEY_PAIRS_START';
export const GET_KEY_PAIRS_SUCCESS = 'GET_KEY_PAIRS_SUCCESS';
export const GET_KEY_PAIRS_FAIL = 'GET_KEY_PAIRS_FAIL';
export const GET_KEY_PAIRS_CLEANUP = 'GET_KEY_PAIRS_CLEANUP';

// get images
export const GET_IMAGES_START = 'GET_IMAGES_START';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAIL = 'GET_IMAGES_FAIL';
export const GET_IMAGES_CLEANUP = 'GET_IMAGES_CLEANUP';

// get flavors
export const GET_FLAVORS_START = 'GET_FLAVORS_START';
export const GET_FLAVORS_SUCCESS = 'GET_FLAVORS_SUCCESS';
export const GET_FLAVORS_FAIL = 'GET_FLAVORS_FAIL';
export const GET_FLAVORS_CLEANUP = 'GET_FLAVORS_CLEANUP';

// create volume
export const CREATE_VOLUME_START = 'CREATE_VOLUME_START';
export const CREATE_VOLUME_SUCCESS = 'CREATE_VOLUME_SUCCESS';
export const CREATE_VOLUME_FAIL = 'CREATE_VOLUME_FAIL';
export const CREATE_VOLUME_CLEANUP = 'CREATE_VOLUME_CLEANUP';

// get volumes
export const GET_VOLUMES_START = 'GET_VOLUMES_START';
export const GET_VOLUMES_SUCCESS = 'GET_VOLUMES_SUCCESS';
export const GET_VOLUMES_FAIL = 'GET_VOLUMES_FAIL';
export const GET_VOLUMES_CLEANUP = 'GET_VOLUMES_CLEANUP';

// get single volume details
export const GET_SINGLE_VOLUME_START = 'GET_SINGLE_VOLUME_START';
export const GET_SINGLE_VOLUME_SUCCESS = 'GET_SINGLE_VOLUME_SUCCESS';
export const GET_SINGLE_VOLUME_FAIL = 'GET_SINGLE_VOLUME_FAIL';
export const GET_SINGLE_VOLUME_CLEANUP = 'GET_SINGLE_VOLUME_CLEANUP';

// delete single volume
export const DELETE_SINGLE_VOLUME_START = 'DELETE_SINGLE_VOLUME_START';
export const DELETE_SINGLE_VOLUME_SUCCESS = 'DELETE_SINGLE_VOLUME_SUCCESS';
export const DELETE_SINGLE_VOLUME_FAIL = 'DELETE_SINGLE_VOLUME_FAIL';
export const DELETE_SINGLE_VOLUME_CLEANUP = 'DELETE_SINGLE_VOLUME_CLEANUP';

// extend single volume size
export const EXTEND_SINGLE_VOLUME_SIZE_START =
  'EXTEND_SINGLE_VOLUME_SIZE_START';
export const EXTEND_SINGLE_VOLUME_SIZE_SUCCESS =
  'EXTEND_SINGLE_VOLUME_SIZE_SUCCESS';
export const EXTEND_SINGLE_VOLUME_SIZE_FAIL = 'EXTEND_SINGLE_VOLUME_SIZE_FAIL';
export const EXTEND_SINGLE_VOLUME_SIZE_CLEANUP =
  'EXTEND_SINGLE_VOLUME_SIZE_CLEANUP';
