// submit a request for account creation for the user
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_CLEANUP = 'REGISTER_CLEANUP';

// allows a user to login once his/her account has been approved
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_CLEANUP = 'LOGIN_CLEANUP';

// get profile
export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const GET_PROFILE_CLEANUP = 'GET_PROFILE_CLEANUP';

// get servers
export const GET_SERVERS_START = 'GET_SERVERS_START';
export const GET_SERVERS_SUCCESS = 'GET_SERVERS_SUCCESS';
export const GET_SERVERS_FAIL = 'GET_SERVERS_FAIL';
export const GET_SERVERS_CLEANUP = 'GET_SERVERS_CLEANUP';

// get single server details
export const GET_SINGLE_SERVER_START = 'GET_SINGLE_SERVER_START';
export const GET_SINGLE_SERVER_SUCCESS = 'GET_SINGLE_SERVER_SUCCESS';
export const GET_SINGLE_SERVER_FAIL = 'GET_SINGLE_SERVER_FAIL';
export const GET_SINGLE_SERVER_CLEANUP = 'GET_SINGLE_SERVER_CLEANUP';

// stop single server
export const STOP_SINGLE_SERVER_START = 'STOP_SINGLE_SERVER_START';
export const STOP_SINGLE_SERVER_SUCCESS = 'STOP_SINGLE_SERVER_SUCCESS';
export const STOP_SINGLE_SERVER_FAIL = 'STOP_SINGLE_SERVER_FAIL';
export const STOP_SINGLE_SERVER_CLEANUP = 'STOP_SINGLE_SERVER_CLEANUP';

// start single server
export const START_SINGLE_SERVER_START = 'START_SINGLE_SERVER_START';
export const START_SINGLE_SERVER_SUCCESS = 'START_SINGLE_SERVER_SUCCESS';
export const START_SINGLE_SERVER_FAIL = 'START_SINGLE_SERVER_FAIL';
export const START_SINGLE_SERVER_CLEANUP = 'START_SINGLE_SERVER_CLEANUP';

// reboot hard single server
export const REBOOT_HARD_SINGLE_SERVER_START = 'REBOOT_HARD_SINGLE_SERVER_START';
export const REBOOT_HARD_SINGLE_SERVER_SUCCESS = 'REBOOT_HARD_SINGLE_SERVER_SUCCESS';
export const REBOOT_HARD_SINGLE_SERVER_FAIL = 'REBOOT_HARD_SINGLE_SERVER_FAIL';
export const REBOOT_HARD_SINGLE_SERVER_CLEANUP = 'REBOOT_HARD_SINGLE_SERVER_CLEANUP';

// reboot soft single server
export const REBOOT_SOFT_SINGLE_SERVER_START = 'REBOOT_SOFT_SINGLE_SERVER_START';
export const REBOOT_SOFT_SINGLE_SERVER_SUCCESS = 'REBOOT_SOFT_SINGLE_SERVER_SUCCESS';
export const REBOOT_SOFT_SINGLE_SERVER_FAIL = 'REBOOT_SOFT_SINGLE_SERVER_FAIL';
export const REBOOT_SOFT_SINGLE_SERVER_CLEANUP = 'REBOOT_SOFT_SINGLE_SERVER_CLEANUP';

// delete single server
export const DELETE_SINGLE_SERVER_START = 'DELETE_SINGLE_SERVER_START';
export const DELETE_SINGLE_SERVER_SUCCESS = 'DELETE_SINGLE_SERVER_SUCCESS';
export const DELETE_SINGLE_SERVER_FAIL = 'DELETE_SINGLE_SERVER_FAIL';
export const DELETE_SINGLE_SERVER_CLEANUP = 'DELETE_SINGLE_SERVER_CLEANUP';